### ISSUE TITLE
When annotation Async and Lock coexist, there will be problems

### ISSUE THREAD

**Issue by chenlingmin** [alturkovic/distributed-lock#14] opened 2020-09-24 10:00 UTC
Like this.

```java
@EventListener
@Async
@RedisLocked
public void sendEmail(XXXEvent event) {
    // do something
}
```

It is recommended not to use the setBeforeExistingAdvisors method，You can detect the presence of AsyncAnnotationBeanPostProcessor.

**Comment by alturkovic** [comment] 2020-09-24 15:44
Could you explain in more details what the issue is please? What kind of problems occur with @Async and @Locked?

**Comment by chenlingmin** [comment] 2020-09-25 02:16
He will cause the lock to be implemented first, and then to enable asynchronous threads.

This will invalidate the lock.



      |        +-------------------------------------------+
      |        | Lock:Thread-1                             |
      |        |    +-----------------------------------+  |
      |        |    | Async:Thread-2                    |  |
      |        |    |   +----------------------------+  |  |
      |        |    |   | method:Thread-2            |  |  |
      |        |    |   +----------------------------+  |  |
      |        |    +-----------------------------------+  |
      |        +-------------------------------------------+
      ↓

**Comment by alturkovic** [comment] 2020-10-19 16:10
Sorry for the late reply. You can extract the logic to be locked in a new service and annotate that method using `@RedisLocked` instead. That behaviour is pretty similar to `@Transactional` behaviour to control transactional logic so I am not sure this requires any changes since it can be mitigated.

**Comment by chenlingmin** [comment] 2020-10-20 02:13
Currently, I have changed the Order value of `LockBeanPostProcessor` so that it can work before `AsyncAnnotationBeanPostProcessor`, This solution works. 

Like this 

```java
  @Bean
    public LockBeanPostProcessor lockBeanPostProcessor(
            final ConfigurableBeanFactory configurableBeanFactory,
            final KeyGenerator keyGenerator,
            @Autowired(required = false) final TaskScheduler taskScheduler) {
            LockBeanPostProcessor lockBeanPostProcessor  = new LockBeanPostProcessor(new BeanFactoryAwareIntervalConverter(configurableBeanFactory), configurableBeanFactory::getBean, keyGenerator, taskScheduler);
            lockBeanPostProcessor.setOrder(Ordered.LOWEST_PRECEDENCE - 10);
            return lockBeanPostProcessor;
    }
```

But this method is not elegant enough, it is best to set `LockBeanPostProcessor` according to whether there is `Transactional` or `Async`

**Comment by alturkovic** [comment] 2020-10-20 07:00
I understand your point, but I think you already noticed yourself that it won't really be possible to get the right order for each application. According to a comment [here](https://github.com/spring-projects/spring-framework/issues/24309): Spring project's aspects do not have advice ordering guaranteed. And this is the same argument I am making.

How about something like this:
```

@Autowired
private LockedService lockedService;

@EventListener
@Async
public void sendEmail(XXXEvent event) {
    lockedService.sendEmail(event);
}

class LockedService {

  @RedisLocked
  public void sendEmail(XXXEvent event) {
  }

}
```

**Comment by chenlingmin** [comment] 2020-10-20 08:04
Thank you, your solution is better, but users need to pay attention to the order of aspects.

Expect Spring to provide a more systematic solution.😂

**Comment by alturkovic** [comment] 2020-10-20 12:53
I think we reached an acceptable conclusion so I am going to close this issue for now.

**Closed by alturkovic** 2020-10-20 12:53 UTC
